import {
  applyMultipleSeries,
  colors,
  createCohortPresetFolder,
  SeriesType,
} from "/src/scripts";

export const presets: PresetFolder = {
  id: "hodlers",
  name: "Hodlers",
  tree: [
    {
      id: `hodl-wave`,
      name: `Hodl Wave`,
      title: `Hodl Wave`,
      description: "",
      icon: IconTablerRipple,
      applyPreset(params) {
        return applyMultipleSeries({
          ...params,
          priceScaleOptions: {
            halved: true,
          },
          list: [
            {
              id: "24h",
              title: `24h`,
              color: colors.upTo1d,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToUpTo1dSupplyTotal%All"],
            },
            {
              id: "1d-1w",
              title: `1d to 1w`,
              color: colors.from1dTo1w,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom1dTo7dSupplyTotal%All"],
            },
            {
              id: "1w-1m",
              title: `1w to 1m`,
              color: colors.from1wTo1m,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom7dTo1mSupplyTotal%All"],
            },
            {
              id: "1m-3m",
              title: `1m to 3m`,
              color: colors.from1mTo3m,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom1mTo3mSupplyTotal%All"],
            },
            {
              id: "3m-6m",
              title: `3m to 6m`,
              color: colors.from3mTo6m,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom3mTo6mSupplyTotal%All"],
            },
            {
              id: "6m-1y",
              title: `6m to 1y`,
              color: colors.from6mTo1y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom6mTo1ySupplyTotal%All"],
            },
            {
              id: "1y-2y",
              title: `1y to 2y`,
              color: colors.from1yTo2y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom1yTo2ySupplyTotal%All"],
            },
            {
              id: "2y-3y",
              title: `2y to 3y`,
              color: colors.from2yTo3y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom2yTo3ySupplyTotal%All"],
            },
            {
              id: "3y-5y",
              title: `3y to 5y`,
              color: colors.from3yTo5y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom3yTo5ySupplyTotal%All"],
            },
            {
              id: "5y-7y",
              title: `5y to 7y`,
              color: colors.from5yTo7y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom5yTo7ySupplyTotal%All"],
            },
            {
              id: "7y-10y",
              title: `7y to 10y`,
              color: colors.from7yTo10y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom7yTo10ySupplyTotal%All"],
            },
            {
              id: "10y+",
              title: `10y+`,
              color: colors.from10y,
              seriesType: SeriesType.Stacked,
              dataset: params.datasets["dateToFrom10yToEndSupplyTotal%All"],
            },
          ],
        });
      },
    },
    createCohortPresetFolder({
      id: "sth",
      color: colors.sth,
      name: "STH - Short Term Hodlers",
      datasetKey: "Sth",
    }),
    createCohortPresetFolder({
      id: "lth",
      color: colors.lth,
      name: "LTH - Long Term Hodlers",
      datasetKey: "Lth",
    }),
    {
      id: "up-to-x",
      name: "Up To X",
      tree: [
        createCohortPresetFolder({
          id: "up-to-1d",
          color: colors.white,
          name: "Up To 1 Day",
          datasetKey: "UpTo1d",
        }),
        createCohortPresetFolder({
          id: "up-to-7d",
          color: colors.white,
          name: "Up To 7 Days",
          datasetKey: "UpTo7d",
        }),
        createCohortPresetFolder({
          id: "up-to-1m",
          color: colors.white,
          name: "Up To 1 Month",
          datasetKey: "UpTo1m",
        }),
        createCohortPresetFolder({
          id: "up-to-2m",
          color: colors.white,
          name: "Up To 2 Months",
          datasetKey: "UpTo2m",
        }),
        createCohortPresetFolder({
          id: "up-to-3m",
          color: colors.white,
          name: "Up To 3 Months",
          datasetKey: "UpTo3m",
        }),
        createCohortPresetFolder({
          id: "up-to-4m",
          color: colors.white,
          name: "Up To 4 Months",
          datasetKey: "UpTo4m",
        }),
        createCohortPresetFolder({
          id: "up-to-5m",
          color: colors.white,
          name: "Up To 5 Months",
          datasetKey: "UpTo5m",
        }),
        createCohortPresetFolder({
          id: "up-to-6m",
          color: colors.white,
          name: "Up To 6 Months",
          datasetKey: "UpTo6m",
        }),
        createCohortPresetFolder({
          id: "up-to-1y",
          color: colors.white,
          name: "Up To 1 Year",
          datasetKey: "UpTo1y",
        }),
        createCohortPresetFolder({
          id: "up-to-2y",
          color: colors.white,
          name: "Up To 2 Years",
          datasetKey: "UpTo2y",
        }),
        createCohortPresetFolder({
          id: "up-to-3y",
          color: colors.white,
          name: "Up To 3 Years",
          datasetKey: "UpTo3y",
        }),
        createCohortPresetFolder({
          id: "up-to-5y",
          color: colors.white,
          name: "Up To 5 Years",
          datasetKey: "UpTo5y",
        }),
        createCohortPresetFolder({
          id: "up-to-7y",
          color: colors.white,
          name: "Up To 7 Years",
          datasetKey: "UpTo7y",
        }),
        createCohortPresetFolder({
          id: "up-to-10y",
          color: colors.white,
          name: "Up To 10 Years",
          datasetKey: "UpTo10y",
        }),
      ],
    },
    {
      id: "from-x-to-y",
      name: "From X To Y",
      tree: [
        createCohortPresetFolder({
          id: "from-1d-to-7d",
          color: colors.white,
          name: "From 1 day To 7 days",
          datasetKey: "From1dTo7d",
        }),
        createCohortPresetFolder({
          id: "from-7d-to-1m",
          color: colors.white,
          name: "From 7 days To 1 Month",
          datasetKey: "From7dTo1m",
        }),
        createCohortPresetFolder({
          id: "from-1m-to-3m",
          color: colors.white,
          name: "From 1 Month To 3 Months",
          datasetKey: "From1mTo3m",
        }),
        createCohortPresetFolder({
          id: "from-3m-to-6m",
          color: colors.white,
          name: "From 3 Months To 6 Months",
          datasetKey: "From3mTo6m",
        }),
        createCohortPresetFolder({
          id: "from-6m-to-1y",
          color: colors.white,
          name: "From 6 Months To 1 Year",
          datasetKey: "From6mTo1y",
        }),
        createCohortPresetFolder({
          id: "from-1y-to-2y",
          color: colors.white,
          name: "From 1 Year To 2 Years",
          datasetKey: "From1yTo2y",
        }),
        createCohortPresetFolder({
          id: "from-2y-to-3y",
          color: colors.white,
          name: "From 2 Years To 3 Years",
          datasetKey: "From2yTo3y",
        }),
        createCohortPresetFolder({
          id: "from-3y-to-5y",
          color: colors.white,
          name: "From 3 Years To 5 Years",
          datasetKey: "From3yTo5y",
        }),
        createCohortPresetFolder({
          id: "from-5y-to-7y",
          color: colors.white,
          name: "From 5 Years To 7 Years",
          datasetKey: "From5yTo7y",
        }),
        createCohortPresetFolder({
          id: "from-7y-to-10y",
          color: colors.white,
          name: "From 7 Years To 10 Years",
          datasetKey: "From7yTo10y",
        }),
        createCohortPresetFolder({
          id: "from-10y-to-end",
          color: colors.white,
          name: "From 10 Years To the end",
          datasetKey: "From10yToEnd",
        }),
      ],
    },
    {
      id: "year",
      name: "Years",
      tree: [
        createCohortPresetFolder({
          id: "2009",
          color: colors.white,
          name: "2009",
          datasetKey: "2009",
        }),
        createCohortPresetFolder({
          id: "2010",
          color: colors.white,
          name: "2010",
          datasetKey: "2010",
        }),
        createCohortPresetFolder({
          id: "2011",
          color: colors.white,
          name: "2011",
          datasetKey: "2011",
        }),
        createCohortPresetFolder({
          id: "2012",
          color: colors.white,
          name: "2012",
          datasetKey: "2012",
        }),
        createCohortPresetFolder({
          id: "2013",
          color: colors.white,
          name: "2013",
          datasetKey: "2013",
        }),
        createCohortPresetFolder({
          id: "2014",
          color: colors.white,
          name: "2014",
          datasetKey: "2014",
        }),
        createCohortPresetFolder({
          id: "2015",
          color: colors.white,
          name: "2015",
          datasetKey: "2015",
        }),
        createCohortPresetFolder({
          id: "2016",
          color: colors.white,
          name: "2016",
          datasetKey: "2016",
        }),
        createCohortPresetFolder({
          id: "2017",
          color: colors.white,
          name: "2017",
          datasetKey: "2017",
        }),
        createCohortPresetFolder({
          id: "2018",
          color: colors.white,
          name: "2018",
          datasetKey: "2018",
        }),
        createCohortPresetFolder({
          id: "2019",
          color: colors.white,
          name: "2019",
          datasetKey: "2019",
        }),
        createCohortPresetFolder({
          id: "2020",
          color: colors.white,
          name: "2020",
          datasetKey: "2020",
        }),
        createCohortPresetFolder({
          id: "2021",
          color: colors.white,
          name: "2021",
          datasetKey: "2021",
        }),
        createCohortPresetFolder({
          id: "2022",
          color: colors.white,
          name: "2022",
          datasetKey: "2022",
        }),
        createCohortPresetFolder({
          id: "2023",
          color: colors.white,
          name: "2023",
          datasetKey: "2023",
        }),
        createCohortPresetFolder({
          id: "2024",
          color: colors.white,
          name: "2024",
          datasetKey: "2024",
        }),
      ],
    },
  ],
};
